# hyperparameters.yml
hyperparameters:
  epochs: 10
  batch_size: 32
  validation_split: 0.2
  early_stopping:
    monitor: "val_loss"
    patience: 10
    restore_best_weights: true
  train_test_split:
    test_size: 0.4
    random_state: 42