model:
  name: "water_quality_model"
  layers:
    - type: "Dense"
      units: 64  
      activation: "relu"
      dropout: 0.3
    - type: "Dense"
      units: 32
      activation: "relu" 
      dropout: 0.2
    - type: "Dense"
      units: 16
      activation: "relu"
      dropout: 0.2
    - type: "Dense"
      units: 1
      activation: "sigmoid"
  compile:
    optimizer: "adam"
    loss: "binary_crossentropy"
    metrics:
      - "accuracy"
      - {"class": "Precision", "config": {"thresholds": 0.5}}
      - {"class": "Recall", "config": {"thresholds": 0.5}}
      - {"class": "AUC", "config": {"curve": "ROC"}}
      - {"class": "F1Score", "config": {"threshold": 0.5}}
      - {"class": "TruePositives", "config": {"thresholds": 0.5}}
      - {"class": "TrueNegatives", "config": {"thresholds": 0.5}}
      - {"class": "FalsePositives", "config": {"thresholds": 0.5}}
      - {"class": "FalseNegatives", "config": {"thresholds": 0.5}}
      - {"class": "PrecisionAtRecall", "config": {"recall": 0.8}}
      - {"class": "RecallAtPrecision", "config": {"precision": 0.8}}
      - {"class": "SensitivityAtSpecificity", "config": {"specificity": 0.8}}
      - {"class": "SpecificityAtSensitivity", "config": {"sensitivity": 0.8}}
      - {"class": "FBetaScore", "config": {"beta": 2.0, "threshold": 0.5}}